import Header from "@/Components/Header/Header";
import "./globals.css";
import Footer from "@/Components/Footer/Footer";

export const metadata = {
  title: "Sahil's Portfolio",
  description: "Generated by Me",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="w-3/4 mx-auto relative z-10">
        <Header/>
        </div>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
